# Generated by Django 3.0.6 on 2020-05-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursinary_app', '0004_auto_20200510_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='CODE', max_length=10),
        ),
    ]
