# Generated by Django 3.0.6 on 2020-05-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursinary_app', '0006_auto_20200510_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
        migrations.AddField(
            model_name='course',
            name='course_number',
            field=models.CharField(default='000', max_length=5),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
