# Generated by Django 3.0.6 on 2020-05-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursinary_app', '0007_auto_20200510_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='CODE', max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(default='CODE', max_length=10),
        ),
    ]
