# Generated by Django 3.0.6 on 2020-05-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursinary_app', '0012_auto_20200510_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='text',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='text',
            new_name='subject_name',
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_number',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=4),
        ),
    ]
