# Generated by Django 3.0.6 on 2020-05-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursinary_app', '0013_auto_20200512_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject_name',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_number',
            field=models.CharField(max_length=4),
        ),
    ]
